$:
  vscode:
    - runner:
        cpus: 4
        tags: cnb:arch:amd64
      docker:
        image: docker.cnb.cool/zishuo/default-dev-env:latest
      imports: https://cnb.cool/zishuo/system-env/-/blob/main/envs/init.yml
      env:
        GOBUILD_WELCOME_CMD: |
          init-ai-config
      services:
        - vscode
        - name: docker
          options:
            rootlessBuildkitd:
              enabled: true
      stages:
        - name: Install Tools or Plugins
          script: |
            if [ -e "/workspace/.scripts/install.sh" ]; then
                bash /workspace/.scripts/install.sh
            fi
        - name: Wait for Vscode
          type: vscode:go
        - name: Claude Code Update
          script: |
            claude update
        - name: OpenAI Codex Update
          script: |
            bun install -g @openai/codex@latest
        - name: Install MCP Tools
          script: |
            uv tool install --from git+https://github.com/oraios/serena serena-agent
            uv tool install --from git+https://github.com/sparfenyuk/mcp-proxy mcp-proxy
            bun install -g tdd-guard@latest
            bun install -g mcp-remote@latest
            bun install -g repomix@latest
            bun install -g @fission-ai/openspec@latest
